// <auto-generated />
using System;
using JobLeet.WebApi.JobLeet.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobLeet.WebApi.Migrations
{
    [DbContext(typeof(BaseDBContext))]
    [Migration("20241026062820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Accounts.V1.LoginUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("loginuser_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccountCreated")
                        .HasColumnType("boolean")
                        .HasColumnName("loginuser_accountcreated");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("integer")
                        .HasColumnName("loginuser_accountstatus");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loginuser_address");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text")
                        .HasColumnName("loginuser_ipaddress");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loginuser_logintime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loginuser_password");

                    b.Property<int?>("PersonNameId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("loginuser_role");

                    b.HasKey("Id");

                    b.HasIndex("PersonNameId");

                    b.ToTable("jblt_loginuser", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Accounts.V1.RegisterUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("jblt_registerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasMaxLength(101)
                        .HasColumnType("character varying(101)")
                        .HasColumnName("jblt_confirmpassword");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(101)
                        .HasColumnType("character varying(101)")
                        .HasColumnName("jblt_password");

                    b.Property<int>("PersonNameId")
                        .HasColumnType("integer");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<int>("UserEmailId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonNameId");

                    b.HasIndex("UserEmailId");

                    b.ToTable("jblt_registerUser", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Accounts.V1.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_roleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleName")
                        .HasColumnType("integer")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("jblt_role", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("address_city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_country");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("address_postalCode");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("address_state");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("address_street");

                    b.HasKey("Id");

                    b.ToTable("jblt_userAddress", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("education_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cgpa")
                        .HasColumnType("numeric")
                        .HasColumnName("education_cgpa");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("education_degree");

                    b.Property<DateOnly>("GraduationDate")
                        .HasColumnType("date")
                        .HasColumnName("education_graduationdate");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("education_nstitution");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("education_major");

                    b.HasKey("Id");

                    b.ToTable("jblt_education", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("email_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<int>("EmailType")
                        .HasColumnType("integer")
                        .HasColumnName("email_type");

                    b.HasKey("Id");

                    b.ToTable("jblt_email", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("experience_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("experience_type");

                    b.HasKey("Id");

                    b.ToTable("jblt_experience", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.PersonName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("personname_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("personName_firstname");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("personName_lastname");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("personName_middlename");

                    b.HasKey("Id");

                    b.ToTable("jblt_personName", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("jblt_phoneid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryCode")
                        .HasColumnType("integer")
                        .HasColumnName("jblt_countrycode");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("jblt_phonenumber");

                    b.HasKey("Id");

                    b.ToTable("jblt_phone", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("qualification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QualificationInformation")
                        .HasColumnType("text")
                        .HasColumnName("qualification_information");

                    b.Property<int>("QualificationType")
                        .HasColumnType("integer")
                        .HasColumnName("qualification_type");

                    b.HasKey("Id");

                    b.ToTable("jblt_qualification", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("jblt_skill", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Companies.V1.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("jblt_company", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Companies.V1.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("companyprofile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyAddressId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContactEmailId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContactPhoneId")
                        .HasColumnType("integer");

                    b.Property<int?>("IndustryType")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileInfo")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("company_website");

                    b.HasKey("Id");

                    b.HasIndex("CompanyAddressId");

                    b.HasIndex("ContactEmailId");

                    b.HasIndex("ContactPhoneId");

                    b.ToTable("jblt_companyprofile", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Jobs.V1.JobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApplicationDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("job_applicationdeadline");

                    b.Property<string>("BasicPay")
                        .HasColumnType("text")
                        .HasColumnName("job_basic_pay");

                    b.Property<string>("Benefits")
                        .HasColumnType("text")
                        .HasColumnName("job_benefits");

                    b.Property<int?>("CompanyDescriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("FunctionalArea")
                        .HasColumnType("text")
                        .HasColumnName("job_functional_area");

                    b.Property<int?>("JobAddressId")
                        .HasColumnType("integer");

                    b.Property<string>("JobDescription")
                        .HasColumnType("text")
                        .HasColumnName("job_description");

                    b.Property<string>("JobResponsibilities")
                        .HasColumnType("text")
                        .HasColumnName("job_responsibility");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<string>("JobType")
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("job_posting_date");

                    b.Property<string>("PreferredQualifications")
                        .HasColumnType("text")
                        .HasColumnName("preferred_qualifications");

                    b.Property<int?>("RequiredExperienceId")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredQualificationId")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillsRequiredId")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("job_tags");

                    b.Property<int?>("Vacancies")
                        .HasColumnType("integer")
                        .HasColumnName("job_vacancies");

                    b.Property<string>("WorkEnvironment")
                        .HasColumnType("text")
                        .HasColumnName("job_workenvironment");

                    b.HasKey("Id");

                    b.HasIndex("CompanyDescriptionId");

                    b.HasIndex("JobAddressId");

                    b.HasIndex("RequiredExperienceId");

                    b.HasIndex("RequiredQualificationId");

                    b.HasIndex("SkillsRequiredId");

                    b.ToTable("jblt_job", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Seekers.V1.Seeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("seeker_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Achievements")
                        .HasColumnType("text")
                        .HasColumnName("job_achievements");

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seeker_dob");

                    b.Property<int?>("EducationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<string>("Interests")
                        .HasColumnType("text")
                        .HasColumnName("job_interests");

                    b.Property<string>("LinkedInProfile")
                        .HasColumnType("text")
                        .HasColumnName("seeker_linkedin");

                    b.Property<int?>("PhoneId")
                        .HasColumnType("integer");

                    b.Property<string>("Portfolio")
                        .HasColumnType("text");

                    b.Property<string>("ProfileSummary")
                        .HasColumnType("text")
                        .HasColumnName("seeker_profilesummary");

                    b.Property<int?>("QualificationsId")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("EducationId");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("PhoneId");

                    b.HasIndex("QualificationsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("jblt_seeker", (string)null);
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Accounts.V1.LoginUser", b =>
                {
                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.PersonName", "PersonName")
                        .WithMany()
                        .HasForeignKey("PersonNameId");

                    b.OwnsOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.MetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("LoginUserId")
                                .HasColumnType("integer");

                            b1.HasKey("LoginUserId");

                            b1.ToTable("jblt_loginuser");

                            b1.WithOwner()
                                .HasForeignKey("LoginUserId");
                        });

                    b.Navigation("MetaData")
                        .IsRequired();

                    b.Navigation("PersonName");
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Accounts.V1.RegisterUser", b =>
                {
                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.PersonName", "PersonName")
                        .WithMany()
                        .HasForeignKey("PersonNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Email", "UserEmail")
                        .WithMany()
                        .HasForeignKey("UserEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.MetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("RegisterUserId")
                                .HasColumnType("integer");

                            b1.HasKey("RegisterUserId");

                            b1.ToTable("jblt_registerUser");

                            b1.WithOwner()
                                .HasForeignKey("RegisterUserId");
                        });

                    b.Navigation("MetaData")
                        .IsRequired();

                    b.Navigation("PersonName");

                    b.Navigation("UserEmail");
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Accounts.V1.Role", b =>
                {
                    b.OwnsOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.MetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("RoleId")
                                .HasColumnType("integer");

                            b1.HasKey("RoleId");

                            b1.ToTable("jblt_role");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("MetaData")
                        .IsRequired();
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Education", b =>
                {
                    b.OwnsOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.MetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("EducationId")
                                .HasColumnType("integer");

                            b1.HasKey("EducationId");

                            b1.ToTable("jblt_education");

                            b1.WithOwner()
                                .HasForeignKey("EducationId");
                        });

                    b.Navigation("MetaData")
                        .IsRequired();
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Experience", b =>
                {
                    b.OwnsOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.MetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("ExperienceId")
                                .HasColumnType("integer");

                            b1.HasKey("ExperienceId");

                            b1.ToTable("jblt_experience");

                            b1.WithOwner()
                                .HasForeignKey("ExperienceId");
                        });

                    b.Navigation("MetaData")
                        .IsRequired();
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Phone", b =>
                {
                    b.OwnsOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.MetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("PhoneId")
                                .HasColumnType("integer");

                            b1.HasKey("PhoneId");

                            b1.ToTable("jblt_phone");

                            b1.WithOwner()
                                .HasForeignKey("PhoneId");
                        });

                    b.Navigation("MetaData")
                        .IsRequired();
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Qualification", b =>
                {
                    b.OwnsOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.MetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("QualificationId")
                                .HasColumnType("integer");

                            b1.HasKey("QualificationId");

                            b1.ToTable("jblt_qualification");

                            b1.WithOwner()
                                .HasForeignKey("QualificationId");
                        });

                    b.Navigation("MetaData")
                        .IsRequired();
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Skill", b =>
                {
                    b.OwnsOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.MetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("SkillId")
                                .HasColumnType("integer");

                            b1.HasKey("SkillId");

                            b1.ToTable("jblt_skill");

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.Navigation("MetaData")
                        .IsRequired();
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Companies.V1.Company", b =>
                {
                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Companies.V1.CompanyProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Companies.V1.CompanyProfile", b =>
                {
                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Address", "CompanyAddress")
                        .WithMany()
                        .HasForeignKey("CompanyAddressId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Email", "ContactEmail")
                        .WithMany()
                        .HasForeignKey("ContactEmailId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Phone", "ContactPhone")
                        .WithMany()
                        .HasForeignKey("ContactPhoneId");

                    b.Navigation("CompanyAddress");

                    b.Navigation("ContactEmail");

                    b.Navigation("ContactPhone");
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Jobs.V1.JobEntity", b =>
                {
                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Companies.V1.Company", "CompanyDescription")
                        .WithMany()
                        .HasForeignKey("CompanyDescriptionId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Address", "JobAddress")
                        .WithMany()
                        .HasForeignKey("JobAddressId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Experience", "RequiredExperience")
                        .WithMany()
                        .HasForeignKey("RequiredExperienceId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Qualification", "RequiredQualification")
                        .WithMany()
                        .HasForeignKey("RequiredQualificationId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Skill", "SkillsRequired")
                        .WithMany()
                        .HasForeignKey("SkillsRequiredId");

                    b.Navigation("CompanyDescription");

                    b.Navigation("JobAddress");

                    b.Navigation("RequiredExperience");

                    b.Navigation("RequiredQualification");

                    b.Navigation("SkillsRequired");
                });

            modelBuilder.Entity("JobLeet.WebApi.JobLeet.Core.Entities.Seekers.V1.Seeker", b =>
                {
                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Qualification", "Qualifications")
                        .WithMany()
                        .HasForeignKey("QualificationsId");

                    b.HasOne("JobLeet.WebApi.JobLeet.Core.Entities.Common.V1.Skill", "Skills")
                        .WithMany()
                        .HasForeignKey("SkillsId");

                    b.Navigation("Address");

                    b.Navigation("Education");

                    b.Navigation("Experience");

                    b.Navigation("Phone");

                    b.Navigation("Qualifications");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
